ProductApp/Models/Category.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ProductApp.Models
{
    public class Category
    {
        [Key]
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
        public string CategoryDetails { get; set; }
        public List<Product> Products { get; set; }
    }
}

ProductApp/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProductApp.Models;
using System.Linq;

namespace ProductApp.Controllers
{
    public class CategoryController : Controller
    {
        Context c = new Context();
        [Authorize]
        public IActionResult Index()
        {
            var cat = c.TB_CATEGORIES.ToList();
            return View(cat);
        }

        [HttpGet]
        public IActionResult AddCategory()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddCategory(Category category)
        {
            c.TB_CATEGORIES.Add(category);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult DeleteCategory(int ID)
        {
            var categoryToDelete = c.TB_CATEGORIES.Find(ID);
            if (categoryToDelete != null)
            {
                c.TB_CATEGORIES.Remove(categoryToDelete);
                c.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        public IActionResult GetCategory(int ID)
        {
            var categoryToGet = c.TB_CATEGORIES.Find(ID);
            return View("GetCategory", categoryToGet);
        }
        public IActionResult UpdateCategory(Category category)
        {
            var categoryToUpdate = c.TB_CATEGORIES.Find(category.CategoryID);
            if (categoryToUpdate != null)
            {
                categoryToUpdate.CategoryName = category.CategoryName;
                c.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        //public IActionResult GoCategoryDetails(int ID)
        //{
        //    var products = c.TB_PRODUCTS.Include(x => x.Category).ToList().Where(x => x.Category.CategoryID == ID).ToList();
        //    return RedirectToAction("/Product/Index/", ID);
        //}
    }
}
    

ProductApp/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProductApp.Models;
using System.Collections.Generic;
using System.Linq;

namespace ProductApp.Controllers
{
    public class ProductController : Controller
    {
        Context c = new Context();
        public IActionResult Index(int ID)
        {
            var productList = c.TB_PRODUCTS.Include(x => x.Category).ToList().Where(x => x.Category.CategoryID == ID).ToList();
            if (productList == null || productList.Count == 0)
            {
                var pr = c.TB_PRODUCTS.Include(x => x.Category).ToList();
                return View(pr);
            }
            else
            {
                var pr = productList;
                return View(pr);
            }
        }

        [HttpGet]
        public IActionResult AddProduct()
        {
            List<SelectListItem> cats = (from x in c.TB_CATEGORIES.ToList()
                                         select new SelectListItem
                                         {
                                             Text = x.CategoryName,
                                             Value = x.CategoryID.ToString()
                                         }).ToList();
            ViewBag.Categories = cats;
            return View();
        }
        [HttpPost]
        public IActionResult AddProduct(Product product)
        {
            /*Take related table values*/
            var cat = c.TB_CATEGORIES.Where(x => x.CategoryID == product.Category.CategoryID).FirstOrDefault();
            product.Category = cat;

            c.TB_PRODUCTS.Add(product);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

ProductApp/Views/Category/AddCategory.cshtml
@model ProductApp.Models.Category

@{
    ViewData["Title"] = "AddCategory";
    Layout = "~/Views/Shared/_LayoutNavbar.cshtml";
}

<h2>Adding Category</h2>

<form class="form-group" method="post">
    <b>Category Name</b>

    @Html.TextBoxFor(x=>x.CategoryName, new{@class="form-control"})

    <br />

    <button href="/Category/AddCategory" class="btn btn-success">Add</button>
</form>

ProductApp/Views/Category/GetCategory.cshtml
@model ProductApp.Models.Category

@{
    ViewData["Title"] = "GetCategory";
    Layout = "~/Views/Shared/_LayoutNavbar.cshtml";
}

<h2>GetCategory</h2>

@using (Html.BeginForm("UpdateCategory","Category",FormMethod.Post))
{
    <b>Category ID</b>

    @Html.TextBoxFor(x=>x.CategoryID, new{@class="form-control"})

    <br />
    <b>Category Name</b>

    @Html.TextBoxFor(x=>x.CategoryName, new{@class="form-control"})

    <br />

    <button href="/Category/UpdateCategory" class="btn btn-success">Update</button>
}

ProductApp/Views/Category/Index.cshtml
@model List<ProductApp.Models.Category>

@{
    ViewData["Title"] = "Category";
    Layout = "~/Views/Shared/_LayoutNavbar.cshtml";
}

<h2>Category</h2>


    <br />

    <div>
        <table class="table table-bordered">
            <tr>
                <th>Category ID</th>
                <th>Category Name</th>
                <th>Operations</th>
            </tr>
            <tbody>
                @foreach (var cat in Model)
                {
                    <tr>
                        <td>@cat.CategoryID</td>
                        <td>@cat.CategoryName</td>
                        <td>
                            <a href="/Category/DeleteCategory/@cat.CategoryID" class="btn btn-danger">Delete</a>
                            <a href="/Category/GetCategory/@cat.CategoryID" class="btn btn-success">Update</a>
                            @Html.ActionLink("Details", "Index", "Product", 
                                new { ID = @cat.CategoryID }, 
                                new { @class = "btn btn-primary"})
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <a href="/Category/AddCategory" class="btn btn-info">Add New Category</a>
    </div>